/** Open a printable salary advice / payslip window. */
export function openPayslipPrintWindow(payslip) {
  const snap = payslip?.snapshot || {}
  const run = payslip?.pay_run || {}
  const period = run.period_year
    ? `${run.period_year}-${String(run.period_month).padStart(2, '0')}`
    : `${snap.period_year}-${String(snap.period_month).padStart(2, '0')}`
  const payday = run.payday || snap.payday || ''
  const benefits = snap.benefits || []
  const advances = snap.advances || []

  const benefitRows = benefits
    .map(
      (b) =>
        `<tr><td>${escapeHtml(b.name)}</td><td style="text-align:right">${formatMoney(b.amount)}</td></tr>`,
    )
    .join('')
  const advanceRows = advances
    .map(
      (a) =>
        `<tr><td>Salary advance (${escapeHtml(a.date || '')})</td><td style="text-align:right">(${formatMoney(a.amount)})</td></tr>`,
    )
    .join('')

  const html = `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Payslip ${escapeHtml(period)}</title>
  <style>
    body { font-family: Georgia, serif; color: #111; margin: 32px; }
    h1 { font-size: 22px; margin: 0 0 4px; }
    .muted { color: #555; font-size: 13px; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th, td { padding: 8px 6px; border-bottom: 1px solid #ddd; font-size: 14px; }
    th { text-align: left; color: #444; font-weight: 600; }
    .totals td { font-weight: 700; border-top: 2px solid #111; }
    @media print { body { margin: 12mm; } }
  </style>
</head>
<body>
  <h1>iTreq Inc — Salary advice</h1>
  <p class="muted">Period ${escapeHtml(period)} · Payday ${escapeHtml(String(payday).slice(0, 10))}</p>
  <p><strong>${escapeHtml(snap.staff_name || '')}</strong><br/>
  <span class="muted">${escapeHtml(snap.job_title || payslip.job_title || '')}</span><br/>
  <span class="muted">${escapeHtml(snap.email || '')}</span></p>
  <table>
    <thead><tr><th>Description</th><th style="text-align:right">Amount (BWP)</th></tr></thead>
    <tbody>
      <tr><td>Basic salary</td><td style="text-align:right">${formatMoney(snap.base_salary ?? payslip.base_salary)}</td></tr>
      ${benefitRows}
      ${advanceRows}
      <tr class="totals"><td>Gross</td><td style="text-align:right">${formatMoney(snap.gross ?? payslip.gross)}</td></tr>
      <tr class="totals"><td>Net pay</td><td style="text-align:right">${formatMoney(snap.net ?? payslip.net)}</td></tr>
    </tbody>
  </table>
  <p class="muted" style="margin-top:24px">Generated by iTreq Inc ops</p>
  <script>window.onload = function () { window.print(); }</script>
</body>
</html>`

  const w = window.open('', '_blank')
  if (!w) return false
  w.document.open()
  w.document.write(html)
  w.document.close()
  return true
}

function formatMoney(n) {
  const v = Number(n) || 0
  return v.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })
}

function escapeHtml(s) {
  return String(s || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}
